version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: https://laravel-playwright-cicd-automation-project.onrender.com
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sql12775461
      DB_USERNAME: sql12775461
      DB_PASSWORD: HLv5Vc77pJ
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql12775461
      MYSQL_USER: sql12775461
      MYSQL_PASSWORD: HLv5Vc77pJ
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
