version: '3.8'

services:
  app:
    build:
      context: .  # this means it uses the current directory (backend folder in your case)
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html  # Ensure the app files are correctly linked
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: https://laravel-playwright-cicd-automation-project.onrender.com
      DB_CONNECTION: mysql
      DB_HOST: sql12.freesqldatabase.com
      DB_PORT: 3306
      DB_DATABASE: sql12775461
      DB_USERNAME: sql12775461
      DB_PASSWORD: HLv5Vc77pJ
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
