name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo, pdo_mysql, mbstring, bcmath

    - name: Install Laravel dependencies
      run: |
        cd backend
        composer install --no-progress
        cp .env.example .env
        php artisan key:generate

    - name: Configure .env with remote DB
      run: |
        cd backend
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=sql12.freesqldatabase.com" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=sql12775461" >> .env
        echo "DB_USERNAME=sql12775461" >> .env
        echo "DB_PASSWORD=HLv5Vc77pJ" >> .env

    - name: Run Laravel migrations
      run: |
        cd backend
        php artisan migrate --force

    - name: Start Laravel server
      run: |
        cd backend
        php artisan serve --host=0.0.0.0 --port=8000 &
