name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo, pdo_mysql, mbstring, bcmath

    # Set up Node.js for Playwright
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install Laravel dependencies
    - name: Install Laravel dependencies
      run: |
        cd backend
        composer install --no-progress
        cp .env.example .env
        php artisan key:generate

    # Configure .env with remote DB and port
    - name: Configure .env with remote DB
      run: |
        cd backend
        echo "APP_URL=http://127.0.0.1:10000" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=sql12.freesqldatabase.com" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=sql12775461" >> .env
        echo "DB_USERNAME=sql12775461" >> .env
        echo "DB_PASSWORD=HLv5Vc77pJ" >> .env

    # Run Laravel migrations
    - name: Run Laravel migrations
      run: |
        cd backend
        php artisan migrate --force

    # Start Laravel server
    - name: Start Laravel server
      run: |
        cd backend
        php artisan serve --host=127.0.0.1 --port=10000 &
        sleep 10

    # Install Playwright dependencies
    - name: Install Playwright dependencies
      run: |
        cd frontend
        npm ci
        npx playwright install --with-deps

    # Run Playwright tests
    - name: Run Playwright tests
      run: |
        cd frontend
        npx playwright test
